name: Docker

on:
    push:
        branches:
            - "master"
        tags:
            - "*"
    workflow_dispatch:

jobs:
  publish_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push - API
        uses: docker/build-push-action@v3
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/janderedev/automod-api:latest
            ghcr.io/janderedev/automod-api:${{ GITHUB_SHA }}

  publish_web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push - Web
        uses: docker/build-push-action@v3
        with:
          context: ./web
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/janderedev/automod-web:latest
            ghcr.io/janderedev/automod-web:${{ GITHUB_SHA }}

  publish_bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push - Bridge
        uses: docker/build-push-action@v3
        with:
          context: ./bridge
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/janderedev/automod-bridge:latest
            ghcr.io/janderedev/automod-bridge:${{ GITHUB_SHA }}
          
  publish_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push - Bot
        uses: docker/build-push-action@v3
        with:
          context: ./bot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/janderedev/automod-bot:latest
            ghcr.io/janderedev/automod-bot:${{ GITHUB_SHA }}
